DLS-9979 - improve session request id logging
hmrc/cgt-calculator-non-resident-frontend pull request #264
Opened 2024-02-08 15:10 UTC by TomRafferty

['[CGC Calcs] Improve Session/request ID Logging' (DLS-9979)](https://jira.tools.tax.service.gov.uk/browse/DLS-9979)

2024-02-08 16:01 UTC, johno1985 commented on app/services/SessionCacheService.scala
> +    preservingMdc {
not needed, already present in SessionCache

2024-02-08 16:01 UTC, johno1985 requested changes
minor change

2024-02-08 17:23 UTC, johno1985 commented
Still a few compilation warnings, are you able to resolve some of them?
Also, I think this repo also needs that timeout increasing

2024-02-12 15:23 UTC, PTMGitHub commented
Test this please

2024-02-13 10:44 UTC, mahesh-hmrc reviewed
Overall looks good, just a few comments would be good to address as part of same PR considering the nature of refactoring involved.

2024-02-13 13:35 UTC, TomRafferty commented on test/models/SummaryModelSpec.scala
>  class SummaryModelSpec extends CommonPlaySpec{
So we should consider redoing all the tests or just the ones touched in this branch? Because after looking into what we'd be doing (not familiar with property based testing), it looks like that should be a whole ticket in itself?

2024-02-13 13:38 UTC, TomRafferty commented on test/forms/CalculationElectionFormSpec.scala
> -    "with an invalid option" should {
as it's now a sealed trait would it make more sense to remove the form error? Or should we add form error handling into the trait?

2024-02-13 15:21 UTC, mahesh-hmrc commented on test/models/SummaryModelSpec.scala
>  class SummaryModelSpec extends CommonPlaySpec{
tbh, the work in this PR is already out of scope of the ticket it's logged against. So, considering the ticket is a refactoring and we have cleaned up some tests not required due to the type change, it was fair ask to tidy up rest of the tests just in spec to further cleanup

2024-02-14 11:54 UTC, mahesh-hmrc commented on test/models/SummaryModelSpec.scala
>  class SummaryModelSpec extends CommonPlaySpec{
Discussed with Tom that we can address this in separate PR as part of CGT tax year changes

2024-02-15 09:43 UTC, mahesh-hmrc approved these changes

2024-02-15 09:44 UTC, merged